export interface OptionVote {
  optionText: string;
  voteCount: number;
}

export interface Poll {
  // id: number; as the id is auto-generated field, it is not necessary to include it in the model
  id?: number; // Optional, as it is auto-generated by the backend
  question: string;
  options: OptionVote[];
}
